config/routes.rb
Rails.application.routes.draw do
  
  root 'users#my_profile'
  resources :relationships, only: [:create, :destroy]
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :users do
    collection do
      get 'feed', to: 'users#feed', as: :feed
      get 'my_profile', to: 'users#my_profile', as: :my_profile
    end
  	member do
      get :following, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :comments

  has_attached_file :avatar, styles: { medium: "500x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true

  belongs_to :article
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                  class_name:  "Relationship",
                                  dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :articles, dependent: :destroy
  has_many :comments

  has_attached_file :avatar, styles: { medium: "900x300>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  def full_name
    "#{first_name} #{last_name}"
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:username, :email, :first_name, :last_name,:password, :password_confirmation)
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_article, only: %i(show update edit destroy)
  
  def show
    @user = @article.user
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to root_path, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :avatar)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_comment, only: %i(edit destroy)
  before_action :find_article, only: %i(edit create destroy)

  def edit
  end

  def create
    @comment = @article.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@article), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to article_path(@article) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to article_path(@article), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def find_comment
      @comment = Comment.find(params[:id])
    end

    def find_article
      @article = Article.find(params[:article_id])
    end

    def comment_params
      params.require(:comment).permit(:description, :user_id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: %i(following followers show)

  def index
    @users = User.all
  end

  def show
    @articles = @user.articles
  end

  def feed
    @users = current_user.followed_users
    @articles = Article.where(user_id: @users).order(:created_at)
  end

  def my_profile
    @user = current_user
    @articles = @user.articles
  end

  def following
    @title = "Following"
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:email,:first_name,:last_name, :avatar)
    end

    def find_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_image(article, options = { size: 75 })
    gravatar_id = Digest::MD5::hexdigest(current_user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url)
  end
end

app/helpers/user_helper.rb
module UserHelper

  def avatar(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url)
  end

end

app/views/articles/_article.html.erb
  <div class="well">
      <div class="media">
      	<a class="pull-left" href="#">
        <% if article.avatar_file_name.nil?%>
    		  <%= article_image(article)%>
        <% else %>
          <%= image_tag(article.avatar(:thumb))%>
        <% end%>
  		  </a>
  		<div class="media-body">
    		<h4 class="media-heading"><%= link_to article.title, article_path(article)%></h4>
          <p class="text-right">By <%= link_to user.full_name, user_path(user)%></p>
          <p><%= article.content%></p>
          <ul class="list-inline list-unstyled">
  			<li><span><i class="glyphicon glyphicon-calendar"></i> <%= time_ago_in_words(article.created_at) %></span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-comment"></i> 
              <%= link_to article_path(article) do %>
            <%= article.comments.count%> comments
            <% end %> 
            </span>
        </ul>
       </div>

       <% if @user == current_user %>
        <div class="pull-right" >
          <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary'  %>
          <%= link_to 'Delete', article_path(article), method: :delete  , class: 'btn btn-danger'  %>
        </div>
       <% end %>
    </div>
   
  </div>

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading"><%= text %></div>
      <div class="panel-body">
        <div class="field">
    
          <%= f.label :title %>
          <%= f.text_field :title,  class: 'form-control' %>
       
          <%= f.label :content %>
          <%= f.text_area :content,  class: 'form-control' %>
       
          <%= f.label :avatar %>
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
  <br/>
      <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  <%= link_to 'Back', root_path %>

</div>
</div>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article, text: "Edit article" %>

<%# link_to 'Show', @article %> 
<%# link_to 'Back', articles_path %>

app/views/articles/new.html.erb
<%= render 'form', article: @article, text: "New article" %>

app/views/articles/show.html.erb
<% if notice %>
<div class="alert alert-info"><%= notice %></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-8">
        <h1><%= @article.title%></h1>
          <p class="lead">
            by <%= link_to @user.full_name, user_path(@user) %>
          </p>
             <hr>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%=time_ago_in_words(@article.created_at) %></p>
                <hr>
                <% if @article.avatar_file_name.nil?%>
                  <%= article_image(@article, size: 200)%>
                <% else %>
                  <%= image_tag(@article.avatar(:medium))%>
                <% end%>
                <hr>
                <%= @article.content%>
                <hr>
                <%= render 'comments/form', article: @article %>
                <hr>

              <% @article.comments.each do |comment|%>
                <% unless comment.description.nil? %>
                <div class="media">
                    <div class="pull-left">
                        <%= article_image comment.user, size: '50x50'%>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"> <%= comment.user.full_name %>
                            <small><%= time_ago_in_words(comment.created_at)%></small>
                        </h4>
                        <%= comment.description %>
                    </div>
                    <% if current_user == comment.user %>
                      <%= link_to 'edit', edit_article_comment_path(@article,comment) %> 
                      <%= link_to 'delete', article_comment_path(@article, comment), method: :delete,  data: { confirm: 'Are you sure?' }%>
                    <% end %>
                </div>
                <% end %>
              <% end %>
    </div> 

            <div class="col-md-4">
                
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        
        <hr>

</div>

app/views/comments/_form.html.erb
<div class="well">
  <h4>Leave a Comment:</h4>
    <%= form_for [@article, @article.comments.new] do |f| %>
      <div class="form-group">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/comments/_form2.html.erb
<div class="col-lg-6">
<div class="well">
  <h4>Edit Comment:</h4>
    <%= form_for [@article,@comment] do |f| %>
      <div class="form-group">
        <%= f.text_area :description, class: 'form-control' %>
      </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', article_path(@article), class: 'btn btn-primary' %>
	</div>
  <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form2', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <div class="container">
    <%= yield %>
    </div>
    <%# render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
	<div class="row">
		<div class="col-lg-12">
			<p>Copyright &copy; Your Website 2017</p>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Main', root_path, class: 'navbar-brand' %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if current_user %>
                      <li class="navbar-brand"> You are signed as: <%= current_user.full_name %> </li>
                      <li><%= link_to 'Edit user',  edit_user_registration_path(@user) %> </li>
                      <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                      <% else %>
                      <li><%= link_to 'Sign in', new_user_session_path %></li>
                      <li><%= link_to 'Sign up', new_user_registration_path %></li>
                    <% end %>
                </ul> 
            </div>
          </div>
    </nav>

app/views/users/_user_info.html.erb
<section>
      <h1>
        <%= avatar(@user, size: 100) %>
        <br/>
        <%= @user.full_name %>
      </h1>
    </section>
    <section>
      		<div class="stats text-center padding-left">
  					<%= link_to following_user_path(@user) do %>
          	<strong id="following" class="stat">
      					<%= @user.followed_users.count %>
    					</strong>
    						following
  					<% end %>
  							
  				<%= link_to followers_user_path(@user) do %>
          	<strong id="followers" class="stat">
      					<%= @user.followers.count %>
    					</strong>
    					followers
  					<% end %>
					</div>
    </section>

app/views/users/feed.html.erb
<%= link_to "View my profile", user_path(current_user), class: 'btn btn-primary margin-botton'%>
    
<% @articles.each do |article|%>
	<% @user = User.find(article.user_id) %>
  <%= render 'articles/article', :article => article, :user => @user %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%# will_paginate %>

<ul class="users">
   <% @users.each do |user|%>
   <% if current_user != user %>
   <li>
  		<%= avatar(user, size: 52) %>
  		<%= link_to user.full_name, user_path(user) %>
	</li>
<% end %>
<% end %>
</ul>

<%# will_paginate %>

app/views/users/my_profile.html.erb
<% provide(:title, 'My profile') %>

<% if notice %>
<div class="alert alert-info"><%= notice %></div>
<% end %>

<div class="col-lg-4">
  <%= link_to 'All users', users_path, class: 'btn btn-primary'%>  
  <%= link_to 'Feed', feed_users_path, class: 'btn btn-primary'%>  
  <%= render 'user_info' %>
</div>


<div class="col-lg-8">
<%= link_to 'Add article', new_article_path, class: 'btn btn-primary btn-margin'%>


<% @articles.each do |article|%>
  <%= render 'articles/article', :article => article, :user => @user %>
<% end %>
</div>

app/views/users/show.html.erb
<% if notice %>
<div class="alert alert-info"><%= notice %></div>
<% end %>

<div class="col-lg-4">
<section>
      <%= render 'user_info' %>

    <% unless @user == current_user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }) do |f| %>
      <%= f.submit "Unfollow", class: "btn btn-large" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
      <div><%= f.hidden_field :followed_id %></div>
      <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
    <% end %>
  <% end %>
  </div>
<% end %>

</div>

<div class="col-lg-8">
<% if @user == current_user%>
  <%= link_to 'Add article', new_article_path, class: 'btn btn-primary btn-margin'%>
<%end%>

<% @articles.each do |article|%>
  <% @user = User.find(article.user_id) %>
  <%= render 'articles/article', :article => article, :user => @user %>
<% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-lg-4">
    <%= link_to "View my profile", user_path(current_user), class: 'btn btn-primary margin-left'%>
    <%= render 'user_info' %>
    
  </div>
  <div class="col-lg-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <% @users.each do |user|%>
          <li>
            <%= avatar user, size: 52 %>
            <%= link_to user.full_name, user_path(user) %>
          </li>
        <% end %>
      </ul>
      <%# will_paginate %>
    <% end %>
  </div>
</div>